language: node_js
cache: yarn
node_js:
- lts/*
install:
- yarn install
- yarn bootstrap
script:
- yarn build
env:
  matrix:
  - secure: ZTjmWXFlUy1bqTyJMUxfyOxsDdqI8c6DbMDkjn9+W9/u5Zq/f1p9YdwcFbqbI7YuWMrRghoDoQoumCOXlERG3rmWa3QY4faYCAPJcX4r59UP38Rgg+ew+orbd51iYjPdxh8EhO+9CXA4XdFSxkMP1T8sa0nAzlLQRNU9VXe/KKdsaKtVPjewxLyMjtSSxrz05GCnTaDE7NLoF46OpbIC+oJfYcQhTjZgFsUo1y0Y7FI4fyK5e97D9aGeLiRx+QNWUDjwPHz7D92RGeIUimJwiHqJVCqogPPJdr6xb/TKIF0M9ON5D2RdYRpFm+OyY5dktVeCvxOtzknGxClzhGxLNaYmx1J8e1PXqQ2Vrxzu80MbK6GJNT1koMfkIbrEtPFugABOY1ME1xweCZk7C9ooiboLcCzSzzbYHjyCgB2VhhortpUh9fcVWew976djRsSp4J31+/lZl4WXBIPlLL7QYBvQ7He2yvSgF94f1W9v6V6blG17p3Gek20Ebv3EoaSWjJYTnvuinqXEimSLji6S1gYzQjjf/BU+BvmLb6UoNok+lECOKTIbxPPwTueaJe9MoKEyEuF8x7K0SuOhJNKqZY79kx7WoB9IFaOc9LRTVLUi3/zPOvxlH40W0odRnYxqlpUrSCTZosvzpkwegUjl8SmCE8zz1vmrtDFMY60lOjs=
after_success:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
- git remote add pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- git fetch pub master
- git checkout master
- git status
- 'git commit -a -m "docs: update readme [ci skip]"'
- git push
deploy:
  provider: script
  script: yarn lerna publish --git-remote pub
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
